USE COLLEGE;
DROP PROCEDURE IF EXISTS COLLEGE.SP_USER_UPDATE_XML;
CREATE PROCEDURE COLLEGE.`SP_USER_UPDATE_XML`(sXML LONGTEXT)
BEGIN
  DECLARE iCount INT DEFAULT 1;
  DECLARE iRowCount INT DEFAULT 0;
  
  SET iRowCount = EXTRACTVALUE(sXML, 'COUNT(//USER//ROWS)');
  
  WHILE iCount <= iRowCount DO
    UPDATE USER_MAST SET  
                USER_LOC = TRIM(EXTRACTVALUE(sXML, '//ROWS[$iCount]//USER_LOC')), 
                USER_EMAIL = TRIM(EXTRACTVALUE(sXML, '//ROWS[$iCount]//USER_EMAIL')), 
                USER_DOB = TRIM(STR_TO_DATE(EXTRACTVALUE(sXML, '//ROWS[$iCount]//USER_DOB'), '%d/%m/%Y')), 
                USER_TYPE = TRIM(EXTRACTVALUE(sXML, '//ROWS[$iCount]//USER_TYPE')), 
                ACTIVE = TRIM(EXTRACTVALUE(sXML, '//ROWS[$iCount]//USER_ACT')),
                USER_PASSWORD = TRIM(EXTRACTVALUE(sXML, '//ROWS[$iCount]//USER_PWD'))
    WHERE USER_ID = TRIM(EXTRACTVALUE(sXML, '//ROWS[$iCount]//USER_ID'));
    
    SET iCount = iCount + 1;
  END WHILE;
  SELECT ROW_COUNT();
END;