USE COLLEGE;
DROP PROCEDURE IF EXISTS COLLEGE.SP_USER_DELETE;
CREATE PROCEDURE COLLEGE.`SP_USER_DELETE`(i_USER_ID INT)
BEGIN
  DELETE FROM USER_MAST 
  WHERE USER_ID = TRIM(i_USER_ID);
  
  SELECT ROW_COUNT(); 
END;

