USE COLLEGE;
DROP PROCEDURE IF EXISTS COLLEGE.SP_USER_UPDATE;
CREATE PROCEDURE COLLEGE.`SP_USER_UPDATE`( 
										s_USER_LOC VARCHAR(30), 
										s_USER_EMAIL VARCHAR(50), 
										s_USER_DOB VARCHAR(10),
										s_USER_TYPE VARCHAR(10), 
										s_USER_ACTIVE VARCHAR(5), 
										s_USER_PASSWORD LONGTEXT,
                    i_USER_ID INT)
BEGIN
  UPDATE USER_MAST SET  
              USER_LOC = TRIM(s_USER_LOC), 
              USER_EMAIL = TRIM(s_USER_EMAIL), 
              USER_DOB = TRIM(STR_TO_DATE(s_USER_DOB, '%d/%m/%Y')), 
              USER_TYPE = TRIM(s_USER_TYPE),
              ACTIVE = TRIM(s_USER_ACTIVE),
              USER_PASSWORD = TRIM(s_USER_PASSWORD)
        WHERE USER_ID = TRIM(i_USER_ID);
  SELECT ROW_COUNT(); 
END;